import pandas as pd
import oracledb as cx_Oracle
import os
import math

# Load cleaned data
DATA_PATH = os.path.join('data', 'all_banks_reviews_analyzed.csv')
df = pd.read_csv(DATA_PATH)

# Oracle connection details
ORACLE_USER = 'BANKREVIEWS'
ORACLE_PASSWORD = 'P@ssw0rd'
ORACLE_DSN = cx_Oracle.makedsn('localhost', 1521, service_name='FREEPDB1')

# Connect to Oracle
conn = cx_Oracle.connect(user=ORACLE_USER, password=ORACLE_PASSWORD, dsn=ORACLE_DSN)
cur = conn.cursor()

# Create tables if not exist
def create_tables():
    cur.execute('''
    BEGIN
        EXECUTE IMMEDIATE 'CREATE TABLE banks (
            bank_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            bank_name VARCHAR2(100) NOT NULL UNIQUE
        )';
    EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
    ''')
    cur.execute('''
    BEGIN
        EXECUTE IMMEDIATE 'CREATE TABLE reviews (
            review_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            bank_id NUMBER REFERENCES banks(bank_id),
            review_text CLOB,
            review_clean CLOB,
            sentiment_label VARCHAR2(20),
            sentiment_score FLOAT,
            themes VARCHAR2(200),
            review_date VARCHAR2(20)
        )';
    EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
    ''')
    conn.commit()

# Insert banks and get their IDs
def get_or_create_bank_id(bank_name):
    cur.execute('SELECT bank_id FROM banks WHERE bank_name = :1', (bank_name,))
    row = cur.fetchone()
    if row:
        return row[0]
    bank_id_var = cur.var(cx_Oracle.NUMBER)
    cur.execute('INSERT INTO banks (bank_name) VALUES (:1) RETURNING bank_id INTO :2', (bank_name, bank_id_var))
    bank_id = bank_id_var.getvalue()
    conn.commit()
    return bank_id

# Insert reviews
def insert_reviews():
    for idx, row in df.iterrows():
        bank_id = get_or_create_bank_id(row['bank'])
        score = row.get('sentiment_score', None)
        # Handle empty, None, nan, NaN as None
        if pd.isna(score) or str(score).strip().lower() in ["", "none", "nan"]:
            score = None
        else:
            try:
                score = float(score)
                if math.isnan(score):
                    score = None
            except (ValueError, TypeError):
                score = None
        try:
            cur.execute('''
                INSERT INTO reviews (bank_id, review_text, review_clean, sentiment_label, sentiment_score, themes, review_date)
                VALUES (:1, :2, :3, :4, :5, :6, :7)
            ''', (
                bank_id,
                row.get('review', ''),
                row.get('review_clean', ''),
                row.get('sentiment_label', ''),
                score,
                row.get('themes', ''),
                str(row.get('review_date', ''))
            ))
        except Exception as e:
            print(f"Error on row {idx}: {e}\nRow data: {row.to_dict()}")
    conn.commit()

if __name__ == '__main__':
    create_tables()
    insert_reviews()
    print('Data inserted successfully.')
    cur.close()
    conn.close()
